### ISSUE TITLE
有问题欢迎反馈呀

### ISSUE THREAD

**Issue by nian-hua** [nian-hua/BumbleBee#1]
welcome

**Comment by Jumbo-WJB** [comment]
测试了800多个任务，报错了
正在向QueueBee注册WokerBee
获取BUMBLEID为72484a159d530d1202580c93e8788a22
Traceback (most recent call last):
  File "main.py", line 88, in <module>
    main()
  File "main.py", line 77, in main
    if GetTaskAndScript():                      #获取脚本及任务
  File "main.py", line 44, in GetTaskAndScript
    print("获取任务列表：{0}....".format(TASK[:20]))
TypeError: 'int' object is not subscriptable

**Comment by nian-hua** [comment]
你的task.txt文件是怎么写的

**Comment by nian-hua** [comment]
可以私聊我一下
